### PR TITLE
Updates coffeelint to 1.16.0

### PR DESCRIPTION
**Pull request by joker-777**
* `rake 12.0.0` raises this error `NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00556216f970b8>`

### CODE REVIEW

**Comment by nhapke** [comment]
Hey, any chance to get this merged?

**Comment by zmbush** [comment]
I'll take a look this weekend.

**Comment by joker-777** [comment]
Thanks @zmbush

**Comment by zmbush** [comment]
Sorry this took so long. I don't really have a lot of time to work on maintaining this gem anymore.

**Pull request merged**
